### ISSUE TITLE
Trouble with installing and running project locally

### ISSUE THREAD

**Issue by jaegz** [netlify/victor-hugo#54]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
`npm install` throws warnings 
`npm start` throws SyntaxError: Unexpected token import

```
λ npm install

> fsevents@1.1.2 install C:\Users\jaegz\test_netlifycms\victor-hugo\node
_modules\fsevents
> node install


> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\jaegz\test_netlifyc
ms\victor-hugo\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> hugo-bin@0.13.0 postinstall C:\Users\jaegz\test_netlifycms\victor-hugo
\node_modules\hugo-bin
> del-cli vendor && node lib/install

  √ Hugo binary is installed successfully
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: caniuse-db@1.0.30000744 (no
de_modules\postcss-cssnext\node_modules\caniuse-db):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Invalid tar header. Maybe t
he tar is corrupted or it needs to be gunzipped?
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-js@https://registry.np
mjs.org/core-js/-/core-js-2.5.0.tgz (node_modules\core-js):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Invalid tar header. Maybe t
he tar is corrupted or it needs to be gunzipped?
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: es5-ext@https://registry.np
mjs.org/es5-ext/-/es5-ext-0.10.26.tgz (node_modules\es5-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Invalid tar header. Maybe t
he tar is corrupted or it needs to be gunzipped?
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: caniuse-lite@1.0.30000744 (
node_modules\caniuse-lite):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Invalid tar header. Maybe t
he tar is corrupted or it needs to be gunzipped?

added 1474 packages in 290.84s
```

```
λ npm start

> victor-hugo@1.0.0 start C:\Users\jaegz\test_netlifycms\victor-hugo
> gulp server

[13:10:01] Failed to load external module babel-register
[13:10:01] Failed to load external module babel-core/register
[13:10:01] Failed to load external module babel/register
C:\Users\jaegz\test_netlifycms\victor-hugo\gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp f
rom "gulp";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (C:\Users\jaegz\test_netlifycms\victor-hu
go\node_modules\gulp\bin\gulp.js:116:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additiona
l logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jaegz\AppData\Roaming\npm-cache\_logs\2017-11-15T1
8_10_01_982Z-debug.log
```

2017-11-15T18_10_01_982Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\jaegz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle victor-hugo@1.0.0~prestart: victor-hugo@1.0.0
6 silly lifecycle victor-hugo@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle victor-hugo@1.0.0~start: victor-hugo@1.0.0
8 verbose lifecycle victor-hugo@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle victor-hugo@1.0.0~start: PATH: C:\Users\jaegz\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\jaegz\test_netlifycms\victor-hugo\node_modules\.bin;C:\Users\jaegz\Downloads\cmder\bin;C:\Users\jaegz\Downloads\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\jaegz\Downloads\cmder\vendor\conemu-maximus5;C:\Users\jaegz\Downloads\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\Windows\System32;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;C:\Ruby193\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files\Amazon\AWSCLI\;C:\Go\bin;C:\Users\jaegz\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\php;C:\curl;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Windows\System32;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Python34;C:\Python34\Scripts;C:\Users\jaegz\AppData\Roaming\Python\Scripts;C:\Hugo\bin;C:\Users\jaegz\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Microsoft VS Code\bin;C:\Users\jaegz\AppData\Roaming\npm;C:\Users\jaegz\bash-scripts;C:\Users\jaegz\AppData\Local\Yarn\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;C:\Users\jaegz\Downloads\cmder\
10 verbose lifecycle victor-hugo@1.0.0~start: CWD: C:\Users\jaegz\test_netlifycms\victor-hugo
11 silly lifecycle victor-hugo@1.0.0~start: Args: [ '/d /s /c', 'gulp server' ]
12 silly lifecycle victor-hugo@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle victor-hugo@1.0.0~start: Failed to exec start script
14 verbose stack Error: victor-hugo@1.0.0 start: `gulp server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\jaegz\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\jaegz\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid victor-hugo@1.0.0
16 verbose cwd C:\Users\jaegz\test_netlifycms\victor-hugo
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jaegz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.9.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error victor-hugo@1.0.0 start: `gulp server`
23 error Exit status 1
24 error Failed at the victor-hugo@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. clone repo
2. npm install
3. npm start

**- What is the expected behavior?**

For npm start to fire up a local dev server

**- Please mention your node.js, NPM, Hugo and operating system version.**
node.js 8.9.1
NPM 5.0.3
Hugo Static Site Generator v0.30.2 windows/amd64 BuildDate: 2017-11-15T13:23:42-05:00
Windows 7 64bit

**Comment by erquhart** [comment]
We weren't installing babel-core directly, which I believe was causing some setups to fail. This should be fixed as of #51 merge - please re-open if not.
