### ISSUE TITLE
Unable to run npm start command

### ISSUE THREAD

**Issue by dfross** [netlify/victor-hugo#7]
Upon cloning the project and successfully running `npm install`, I get the following error after running `npm start`:
```
C:\GitHub\victor-hugo>npm start

> victor-hugo@1.0.0 start C:\GitHub\victor-hugo
> gulp server

[14:20:01] Requiring external module babel-register
[14:20:04] Using gulpfile C:\GitHub\victor-hugo\gulpfile.babel.js
[14:20:04] Starting 'hugo'...
[14:20:04] Starting 'css'...
[14:20:04] Starting 'js'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn hugo ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dfross.AHCM\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victor-hugo@1.0.0 start script 'gulp server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the victor-hugo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs victor-hugo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls victor-hugo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GitHub\victor-hugo\npm-debug.log
```
I am running Windows 10 (64), Node 6.9.0, NPM 3.10.8

**Comment by biilmann** [comment]
Are you sure you have hugo installed and available in the path? It looks like the start command fails to find hugo....

Make sure to follow the install instructions from here: http://gohugo.io/

**Comment by dfross** [comment]
Oh wow. Rookie mistake. You're right! Thanks! Close.
