### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by ccsouthard** [netlify/victor-hugo#9]
I don't believe this is an issue with the theme but with my own setup. Any advice going forward?
 npm start
```

> victor-hugo@1.0.0 start /Users/charliesouthard/Sites/hugo/victor-hugo
> gulp server

[19:47:23] Requiring external module babel-register
[19:47:24] Using gulpfile ~/Sites/hugo/victor-hugo/gulpfile.babel.js
[19:47:24] Starting 'hugo'...
[19:47:24] Starting 'css'...
[19:47:25] Starting 'js'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn hugo ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the victor-hugo@1.0.0 start script 'gulp server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the victor-hugo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs victor-hugo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls victor-hugo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/charliesouthard/Sites/hugo/victor-hugo/npm-debug.log

```
log: https://www.dropbox.com/s/jxfjoe7na4qzjit/npm-debug.log?dl=0

**Comment by ccsouthard** [comment]
Npm issue solved.

**Comment by ianbashford** [comment]
Hi -- I have the same issue running in an alpine docker image -- could you post your solution please?

**Comment by ianbashford** [comment]
For anyone else who gets this, I didn't have the hugo executable on my path -- I simply sym-linked the hugo executable to /usr/local/bin/hugo and that fixed it
